import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import { Toaster } from "@/components/ui/toaster";

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} flex h-dvh flex-col`}>
        <Header />
        <main className="flex-grow overflow-auto bg-neutral-100">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
